- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/EventoController.java
Fiz a altração no editarController do admin para ele herdar de editarControllerGenerico
> Alteração do editar do Admin feita

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/AutorController.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/EventoController.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/model/Evento.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/model/Trilha.java
- aplicacao/contest/src/main/resources/templates/autor/autor_enviar_trabalho_form.html
- aplicacao/contest/src/test/java/ufc/quixada/npi/contest/CadastrarEventosSteps.java
- aplicacao/contest/src/test/java/ufc/quixada/npi/contest/EnviarTrabalhoSteps.java
-Correção nos testes d enviar trabalho e de adicionar trabalho
> -Adicionado trilha na hora de cadasrtar um evento

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/config/SpringSecurityConfig.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/ErrorController.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/model/PapelLdap.java
- aplicacao/contest/src/main/resources/templates/403.html
- Controlador para tratar erros
- Pagina de erro de permissao de acesso 403
> - Controle de Acesso

- aplicacao/contest/src/main/resources/templates/autor/autor_index.html
- aplicacao/contest/src/main/resources/templates/autor/autor_meus_trabalhos.html
Botão participar de evento do aluno agora está condicionado ao período do evento.
Botão adicionar trabalho também foi condicionado ao período de envio inicial e final.
> Cont 47 botao participar evento

- aplicacao/contest/src/main/resources/static/css/time-line-style.css
- aplicacao/contest/src/main/resources/templates/organizador/org_detalhes_evento.html
- aplicacao/contest/src/main/resources/templates/organizador/organizador_meus_eventos.html
Removida informação duplicada e reduzido tamanho da fonte dos textos.
> Redução do espaço ocupado pela timeline.

- aplicacao/contest/src/main/resources/static/css/time-line-style.css
- aplicacao/contest/src/main/resources/templates/autor/autor_index.html
- aplicacao/contest/src/main/resources/templates/autor/autor_meus_trabalhos.html
- aplicacao/contest/src/main/resources/templates/login.html
- aplicacao/contest/src/main/resources/templates/organizador/org_detalhes_evento.html
- aplicacao/contest/src/main/resources/templates/organizador/organizador_meus_eventos.html
Refatoração das timelines, adicionado label datas importantes e alterado o css da timeline.
> Cont 45 corrigir datas pagina listagem eventos professor sta

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/EventoControllerOrganizador.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/service/ParticipacaoEventoService.java
- aplicacao/contest/src/main/resources/templates/organizador/org_eventos_listar_ativos.html
Os botoes Editar e Revisar em um evento agora estão aparecendo de acordo com o papel do usuário logado.
> Cont bug fixes producao

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/EventoControllerOrganizador.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/RevisorController.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/model/Trabalho.java
- aplicacao/contest/src/main/resources/templates/revisor/revisor_avaliar_trabalho.html
* Refatoração retirando a lógica do controller e levando para entidade trabalho
* Atualização na view para se adequar a refatoração
> Ao tentar revisar um trabalho o sistema verifica se o usuário logado foi atribuído como revisor

- aplicacao/contest/src/main/resources/templates/autor/autor_meus_trabalhos.html
- aplicacao/contest/src/main/resources/templates/fragments/evento_timeline.html
Correção da exibição do card-action de enviar trabalhos.
Correção do texto do fragment da timeline.
> Correção da exibição do card-action de enviar trabalhos.

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/EventoControllerOrganizador.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/repository/SubmissaoRepository.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/service/SubmissaoService.java
- aplicacao/contest/src/main/resources/templates/organizador/org_editar_eventos.html
Datas podem ser alteradas de acordo com os períodos do evento.
Corrigido o js de configuração dos datepickers.
> Cont 68 bug permitir mudar datas eventos ativos

- aplicacao/contest/src/main/resources/templates/autor/autor_enviar_trabalho_form.html
> -coreção de bug onde o autor não conseguia enviar um trabalho com

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/EventoControllerOrganizador.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/model/Trabalho.java
- aplicacao/contest/src/main/resources/templates/organizador/org_ver_trabalhos_evento.html
- Organizador do evento pode baixar os trabalhos
> - Certificados é gerado com o nome maiúsculo

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/EventoGenericoController.java
- aplicacao/contest/src/main/resources/templates/organizador/org_editar_eventos.html
Campos de edição de datas de submissão estavam sendo duplicados,  duplicação dos campos removidas!!
> Campos de edição corrigidos, duplicação dos campos removidas!!

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/SecaoController.java
> Correção do RequestMapping dos métodos excluirTrabalho e adicionarTrabalho

- aplicacao/contest/src/main/resources/templates/cadastro.html
- aplicacao/contest/src/main/resources/templates/login.html
criado link para o formulário de cadastro na página inicial e editado a cor do botão de submit no formulário de cadastro.
> create link for page cadastro and edit color button in form cadastro.

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/EventoController.java
> Editar evento corrigido

- aplicacao/contest/src/main/resources/templates/cadastro.html
- aplicacao/contest/src/main/resources/templates/secao/indexSecao.html
paginação feita na página index de seções e recolado disabled no button de cadastro.
> 159 telas contest

- aplicacao/contest/src/main/resources/templates/secao/cadastroSecao.html
- aplicacao/contest/src/main/resources/templates/secao/indexSecao.html
- aplicacao/contest/src/main/resources/templates/secao/secaoTrabalhos.html
adicionado um confirm para confirmar o delete de uma seção. 
cadastro de seção não permite que form seja enviado com campos em branco. 
adicionado mensagem para quando não tiver seção e trabalhos cadastrados em suas respectivas páginas.
botões modal adicionar trabalho arrumados.
> correção de erros nas páginas relatados pelo tester.

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/EventoControllerOrganizador.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/util/Constants.java
- aplicacao/contest/src/main/resources/templates/organizador/org_detalhes_evento.html
Mudança de posição do botão de adicionar organizador e revisor, colocando o botão abaixo do nome dos organizadores e revisores.
> Alteração da posição do botão de adicionar organizador e revisor

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/EventoController.java
- aplicacao/contest/src/main/resources/templates/fragments/header.html
Quando o papel logado for de ADMIN, o dashboard não deverá ser mostrado, já quando o papel logado for de user, ir para início não deve ser exibido, removendo assim o erro de recurso não encontrado que fica para sempre nesse erro.
> Bugfix imagem contest

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/EventoControllerOrganizador.java
- aplicacao/contest/src/main/resources/templates/fragments/footer.html
- aplicacao/contest/src/main/resources/templates/fragments/organizador_menu_navegacao.html
- aplicacao/contest/src/main/resources/templates/organizador/org_detalhes_evento.html
- aplicacao/contest/src/main/resources/templates/organizador/org_trilhas.html
Correções na função convidar pessoa, acontecia dois bugs. Primeiro bug, a função convidar pessoa aparecia em mais de um lugar, essa função só deveria estar na página de detalhes do evento de organizador em específico. Segundo bug, exibia a mensagem de email enviado com sucesso, mesmo sem ter enviado email.
> Corrigindo bugs atrelados a função convidar pessoa

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/config/security/CustomMethodSecurityExpressionRoot.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/AutorController.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/EventoControllerOrganizador.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/LoginController.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/RevisorController.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/exception/ContestException.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/repository/EventoRepository.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/repository/PessoaRepository.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/service/EventoService.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/service/PessoaService.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/util/Constants.java
- aplicacao/contest/src/main/resources/templates/dashboard.html
- aplicacao/contest/src/main/resources/templates/error/403.html
- aplicacao/contest/src/main/resources/templates/fragments/revisor_menu_navegacao.html
- aplicacao/contest/src/main/resources/templates/revisor/revisor_detalhes_evento.html
- aplicacao/contest/src/main/resources/templates/revisor/revisor_eventos_listar_ativos.html
- aplicacao/contest/src/main/resources/templates/revisor/revisor_meus_eventos.html
Alterações da função revisor e remoção do pacote contestException
> #227 refatorar funcionalidade revisor

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/EventoController.java
- aplicacao/contest/src/main/resources/templates/organizador/org_eventos_listar_inativos.html
Inativos. Melhoria do campo Nome do formulário de Adicionar Evento.
> Retirada do botão Editar do card de Ativar Evento na página Eventos

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/model/Evento.java
- aplicacao/contest/src/main/resources/templates/autor/autor_meus_trabalhos.html
Correção do prazo de submissão inicial, pois era possível enviar trabalho antes do período de submissão inicial.
> correção do método que verifica o prazo de submissão inicial

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/config/security/CustomMethodSecurityExpressionRoot.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/AutorController.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/service/EventoService.java
Para revisor e autor do trabalho e organizador do evento.
> Criação do pre autorize para download de arquivo.

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/config/AuthenticationProviderContest.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/service/EventoService.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/util/ContestUtil.java
- aplicacao/contest/src/main/resources/db/migration/V0.3.7__RemoverColunaLocalSecao.sql
Mudança realizada para levar em consideração os usuarios que tenham cadastro incompleto (ausência de cpf)
> Refatoração no Login

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/repository/ParticipacaoEventoRepository.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/service/ParticipacaoEventoService.java
- aplicacao/contest/src/main/resources/templates/autor/autor_listar_trabalhos.html
- aplicacao/contest/src/main/resources/templates/dashboard.html
Ajustado o formulário para reeenvio do trabalho.
> Bugfix reenviar trabalho

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/AutorController.java
- aplicacao/contest/src/main/resources/db/migration/V0.3.7__RemoverColunaLocalSecao.sql
- aplicacao/contest/src/test/java/ufc/quixada/npi/contest/EnviarTrabalhoSteps.java
Ajustado a adição do coautor levando agora em consideração o CPF do coautor.
> Refactoring add coautor in trabalho

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/RevisorController.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/model/Pessoa.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/util/Constants.java
- aplicacao/contest/src/main/resources/templates/revisor/revisor_trabalhos.html
Reverts npi-ufc-qxd/contest#324
> Revert "Adicionando nome de autor e status do trabalho no card revisar trabalho."

- aplicacao/contest/src/main/resources/templates/revisor/revisor_trabalhos.html
> Adicionando os nomes dos autores do trabalho no card de revisar trabalho

- .gitignore
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/service/TrabalhoService.java
- aplicacao/contest/src/main/resources/db/migration/V0.3.7__RemoverColunaLocalSecao.sql
@LeonardoBrendo  tinha um loop infinito no seu código
> Bugfix loop infinito

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/SessaoController.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/repository/TrabalhoRepository.java
- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/service/TrabalhoService.java
- aplicacao/contest/src/main/resources/templates/sessao/sessao_cadastrar.html
- aplicacao/contest/src/main/resources/templates/sessao/sessao_listar_sessoes.html
- aplicacao/contest/src/main/resources/templates/sessao/sessao_ver_trabalhos.html
> 378 organizador pode editar sessao

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/LoginController.java
- aplicacao/contest/src/main/resources/templates/perfil.html
Corrigindo o tratamento de exceção incorreto
> Adicionando nova mensagem de log

- aplicacao/contest/src/main/java/ufc/quixada/npi/contest/controller/RevisorController.java
- aplicacao/contest/src/main/resources/ValidationMessages.properties
- aplicacao/contest/src/main/resources/templates/revisor/revisor_meus_eventos.html
> Removendo verificação de período de revisão
